branches:
  only:
  - master

language: node_js
node_js: 
  - "stable"

before_script:
  - npm run setup
  
script: 
  - npm run build
  - npm run test
  - npm run prettier:check
  - npm run extension:create 
